version: '3.8'

services: 
  database:
    image: mariadb
    container_name: progress-db
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - progressdb_vol:/var/lib/mysql
    networks: 
     - backend-network

  backend:
    build: ./backend
    container_name: progress-api
    ports: 
      - 9080:9080
    environment: 
      DB_URL: //progress-db:3306
    depends_on: 
      - database
    # restart: always
    networks: 
      - backend-network
      - frontend-network

  frontend:
    build: ./frontend
    container_name: progress
    ports: 
      - 80:80
      - 443:443
    environment: 
      API_URL: /api/
      NGINX_BACKEND_URL: progress-api:9080
    depends_on: 
      - backend
    # restart: always
    networks: 
      - frontend-network

volumes: 
  progressdb_vol:

networks: 
  backend-network:
  frontend-network:
